version: "3.8"

services:
  app:
    image: fbs124/g2ss-app:latest
    container_name: g2ss-app
    restart: always
    working_dir: /app

    environment:
      DATABASE_URL: "mysql://g2ss:g2ss@212.227.82.6:3306/g2ss?serverVersion=mariadb-10.6.0"
      MAILER_DSN: "smtp://mailer:1025"
      APP_ENV: "prod"

    entrypoint: /app/entrypoint.sh
    command: sh -lc "php -S 0.0.0.0:8000 -t public"

    ports:
      - "8080:8000"

  mailer:
    image: axllent/mailpit
    container_name: g2ss-mailer
    restart: always
    ports:
      - "8025:8025"
